-- MySQL Script generated by MySQL Workbench
-- Thu Oct 27 12:32:29 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `id_course` VARCHAR(256) NOT NULL,
  `name` VARCHAR(16) NOT NULL,
  `language` VARCHAR(45) NOT NULL,
  `tag_1` VARCHAR(45) NULL,
  `tag_2` VARCHAR(45) NULL,
  `link` VARCHAR(45) NULL,
  `Video_id_video` INT NOT NULL,
  PRIMARY KEY (`id_course`),
  INDEX `fk_course_Video_idx` (`Video_id_video` ASC) VISIBLE,
  CONSTRAINT `fk_course_Video`
    FOREIGN KEY (`Video_id_video`)
    REFERENCES `mydb`.`Video` (`id_video`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Role` (
  `role_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`role_id`));


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `user_id_user` VARCHAR(256) NOT NULL,
  `user_vip` TINYINT NOT NULL,
  PRIMARY KEY (`user_id_user`),
  INDEX `fk_alumne_user1_idx` (`user_id_user` ASC) VISIBLE,
  CONSTRAINT `fk_alumne_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `user_id_user` VARCHAR(256) NOT NULL,
  `dni` VARCHAR(16) NULL,
  `Course_id_course` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`user_id_user`),
  INDEX `fk_teacher_user1_idx` (`user_id_user` ASC) VISIBLE,
  INDEX `fk_Teacher_Course1_idx` (`Course_id_course` ASC) VISIBLE,
  CONSTRAINT `fk_teacher_user1`
    FOREIGN KEY (`user_id_user`)
    REFERENCES `mydb`.`User` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Teacher_Course1`
    FOREIGN KEY (`Course_id_course`)
    REFERENCES `mydb`.`Course` (`id_course`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id_user` VARCHAR(256) NOT NULL,
  `first_name` VARCHAR(45) NULL,
  `last_name` VARCHAR(45) NULL,
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  `active` TINYINT NOT NULL,
  `create_time` TIMESTAMP GENERATED ALWAYS AS () VIRTUAL,
  `user_git` VARCHAR(128) NULL,
  `user_linkedin` VARCHAR(128) NULL,
  `Role_role_id` INT NOT NULL,
  PRIMARY KEY (`id_user`, `Role_role_id`),
  INDEX `fk_User_Role1_idx` (`Role_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_User_Role1`
    FOREIGN KEY (`Role_role_id`)
    REFERENCES `mydb`.`Role` (`role_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `mydb`.`Video`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Video` (
  `id_video` INT NOT NULL,
  `description` VARCHAR(45) NULL,
  `blob` LONGBLOB NULL,
  PRIMARY KEY (`id_video`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
