# Generated by Django 4.2.1 on 2023-05-16 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_user', models.CharField(max_length=256)),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('username', models.CharField(max_length=16)),
                ('email', models.CharField(max_length=256)),
                ('password', models.CharField(max_length=32)),
                ('role', models.CharField(max_length=45)),
                ('reate_time', models.DateTimeField(auto_now_add=True)),
                ('user_git', models.CharField(max_length=128)),
                ('user_linkedin', models.CharField(max_length=128)),
            ],
        ),
    ]
