# Generated by Django 4.2.1 on 2023-05-20 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcapacit', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id_course', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=45)),
                ('languaje', models.CharField(max_length=45)),
                ('tag_1', models.CharField(max_length=45)),
                ('tag_2', models.CharField(max_length=45)),
                ('link', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id_teacher', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='user',
            old_name='reate_time',
            new_name='create_time',
        ),
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AddField(
            model_name='user',
            name='activate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_git',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_linkedin',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=45),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id_video', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(max_length=500)),
                ('blob', models.TextField()),
                ('link', models.CharField(max_length=45)),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcapacit.course')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcapacit.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='teacher',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcapacit.user'),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id_student', models.AutoField(primary_key=True, serialize=False)),
                ('dni', models.IntegerField()),
                ('user_vip', models.BooleanField()),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcapacit.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id_sale', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.CharField(help_text='Ingrese el estado de la compra', max_length=50, null=True)),
                ('discount', models.FloatField(help_text='Descuento')),
                ('value', models.FloatField()),
                ('id_course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcapacit.course')),
                ('id_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcapacit.student')),
                ('id_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcapacit.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id_payment', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('total', models.FloatField()),
                ('id_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcapacit.sale')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='id_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appcapacit.teacher'),
        ),
    ]
